"""first

Revision ID: 118907dfbdeb
Revises: 1388803d55b8
Create Date: 2026-09-18 17:29:11.691486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118907dfbdeb'
down_revision: Union[str, Sequence[str], None] = '1388803d55b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(), nullable=False, server_default=''))
        batch_op.create_unique_constraint('uq_books_isbn', ['isbn'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
